apax/bal/api.py, apax/bal/feature_maps.py, apax/cli/templates/train_config_full.yaml, apax/config/train_config.py, apax/data/initialization.py, apax/data/input_pipeline.py, apax/data/preprocessing.py, apax/data/statistics.py, apax/layers/descriptor/gaussian_moment_descriptor.py, apax/layers/empirical.py, apax/model/builder.py, apax/model/gmnn.py, apax/train/callbacks.py, apax/train/eval.py, apax/train/run.py, tests/regression_tests/apax_config.yaml, tests/unit_tests/data/test_input_pipeline.py, tests/unit_tests/layers/descriptor/test_gaussian_moment_descriptor.py, tests/unit_tests/model/test_apax.py
This PR fixes a bug in the data pipeline where the validation batch size was not used and instead the train batch size was used for everything.
Further:
- I tested the max l2cache option and found it to not do anything, hence I removed it.
- TFPipeline was renamed to AtomisticDataset
- AtomisticDataset is no longer initialized with the batch size
- creating a tf.data dataset from dicts was moved to a separate function
- some type hints
- callback initialization was moved to separate submodule
- the calculation of pairwise distances from cartesian positions was moved from the descriptor and empirical corrections to the energy model. This greatly simplifies the call signature of these models/layers and reduces code duplication.
=> Val bs fix and distance computation refactor

apax/bal/api.py, apax/config/train_config.py, apax/data/input_pipeline.py, apax/data/statistics.py, apax/md/ase_calc.py, apax/md/nvt.py, apax/train/checkpoints.py, apax/train/eval.py, apax/train/run.py, apax/train/trainer.py, tests/integration_tests/md/test_md.py
This PR implements the vmapped training of multiple models at once.
These models can be loaded into the ASE calc for ensembling similarly to training multiple models separately. 
Furthermore, ensembles can now be used in jaxmd.
However, uncertainties are not logged yet.
=> Vmap ensemble training and jaxmd inference

apax/cli/apax_app.py, apax/config/common.py, apax/config/train_config.py, apax/data/initialization.py, apax/md/nvt.py, apax/train/checkpoints.py, apax/train/run.py, apax/train/trainer.py, tests/conftest.py, tests/integration_tests/bal/test_api.py, tests/integration_tests/md/test_md.py
This PR sets the absl log level to WARNING, which prevents absl from spamming the logs with checkpointing information on every epoch.
Logs are now written both to a file under the model path as well as to the terminal.
This will require minor adjustments in IPSuite.
Model version and best path in the data config were  changed to properties and the change was adopted throughout the project
=> Absl logging fix

README.md
#189 
The pinned cuda jax version is causing issues with the latest flax version.
=> unpinned cuda jax version for Flax compatibility

apax/train/checkpoints.py, tests/integration_tests/md/test_model_loading.py
Until now, model loading assumed you are in the same path the training was started from. This has not been a problem since our directories are handled by IPSuite most of the time.
But obviously this was going to cause problems eventually. 
This PR allows models to be loaded from anywhere.
=> implemented model loading from arbitray locations

apax/train/checkpoints.py, tests/integration_tests/md/test_model_loading.py
model loading could cause problems when experiment was set to an empty string since the last release. For IPS compatibility, I've fixed this edge case on the Apax side.
=> added model loading edge case for `experiment=""`

.github/workflows/linting.yaml, apax/config/train_config.py, apax/data/input_pipeline.py, apax/train/metrics.py, apax/train/run.py, apax/train/trainer.py
Added an option to jit multiple train steps using lax.scan to iterate over an additional batch axis. 
The speedups this enables can be significant when training on small structures, when using small batch sizes or both.
It's fully compatible with training ensembles.
=> JIT multiple train steps

apax/md/nvt.py
- added saving of a checkpoint at the end of a simulation. This ensure that any sim can be continued without throwing away a part of the trajectory
- fixed a bug where the ensemble function did not accept a perturbation arg and hence was not able to be used with NPT
=> MD end checkpoint & ensemble NPT fix

.gitignore, README.md, apax/cli/apax_app.py
I have implemented a new CLI command which dumps JSON schemata for the training and MD input files.
These can be included in the vscode settings in order to lint and autocomplete apax input files.
=> Input Autocomplete

.gitignore, README.md, apax/__init__.py, apax/bal/api.py, apax/cli/apax_app.py, apax/config/train_config.py, apax/data/input_pipeline.py, apax/md/ase_calc.py, apax/train/eval.py, apax/train/loss.py, apax/train/run.py, apax/train/trainer.py, apax/utils/convert.py, tests/unit_tests/train/test_loss.py
Reintroduced cached dataset. Choice of ds is now available in input.
=> Cache dataset

apax/cli/templates/train_config_full.yaml, apax/config/lr_config.py, apax/config/train_config.py, apax/layers/empirical.py, apax/optimizer/get_optimizer.py, apax/train/eval.py, apax/train/parameters.py, apax/train/run.py, apax/train/trainer.py, tests/unit_tests/optimizer/test_get_opt.py
Added EMA parameters, replaced my custom SAM implementation with the one in optax (faster and probably more correct) and added a cyclic cosine lr schedule.
todo
=> EMA, SAM update, cyclic LR schedule

apax/config/md_config.py, apax/md/__init__.pyi, apax/md/simulate.py, apax/nodes/md.py, apax/utils/jax_md_reduced/simulate.py
=> NVE bug fix

apax/nodes/__init__.py, apax/nodes/analysis.py, apax/nodes/md.py, apax/nodes/model.py
batch evaluation node suitable for evaluating many differently sized structures. Batch size of 1 is sufficient.
=> implemented apax batch evaluation node

apax/__init__.py, apax/cli/templates/train_config_full.yaml, apax/config/train_config.py, apax/data/input_pipeline.py, apax/train/run.py, apax/utils/convert.py, tests/integration_tests/bal/config.yaml, tests/integration_tests/md/config.yaml, tests/unit_tests/utils/test_convert.py
Adds a dataset which does not use tf.data and pads samples per batch instead of everything to the largest size.
Very advantageous for training datasets containing very differently sized samples.
=> Per Batch Padded Dataset

apax/bal/api.py, apax/cli/templates/train_config_full.yaml, apax/config/train_config.py, apax/layers/descriptor/basis_functions.py, apax/md/ase_calc.py, apax/md/simulate.py, apax/model/builder.py, apax/train/eval.py, apax/train/run.py, tests/integration_tests/bal/config.yaml, tests/integration_tests/md/config.yaml, tests/integration_tests/md/test_md.py, tests/integration_tests/transfer_learning/config_base.yaml, tests/integration_tests/transfer_learning/config_ft.yaml, tests/nodes/example.yaml, tests/regression_tests/apax_config.yaml
Reworked choosing the basis function and added the non-orthogonalized bessel basis of Kocer https://arxiv.org/pdf/1907.02384
I've found it to yield lower validation losses at no extra cost.
=> New Basis function interface

apax/config/train_config.py, apax/data/input_pipeline.py
by reinitializing the processpoolexcecutor every couple of epochs, we avoid a memory leak.
Not entirely sure what causes it in the first place but this is the simplest solution I can think of. 
While reinitializing every epoch is perfectly fine for large datasets, small datasets can get a slight performance hit when restarting the processes all the time.
Since even MP/SPICE can go for more than 10 epochs just fine, I think it's okay to hardcode it to 10.
=> fixed memory leak in pbp ds

apax/md/io.py
with https://github.com/MDAnalysis/mdanalysis/pull/4615 MDAnalyis only supports `store=time`.
This is also testes here https://github.com/zincware/ZnH5MD/blob/e3f08c2a57355a853e66c51150b9a919060ddb2b/tests/test_mda.py#L19
Most files that we generate will not be analyzed through MDAnalysis but the trajectory files are an exception. As long as MDAnalysis does not support fixed time / step information I'd suggest using this configuration and accept that it will produce slightly larger files for the convenience of being able to analyze them more easily.
=> use `store="time"`

apax/md/ase_calc.py
Fix a bug in the batch_eval code that causes the wrong atoms to be copied
=> fix `batch_eval`

apax/md/io.py
MDAnalysis can not deal with e.g. "Angstrom/fs" units for velocities. Thus we disable this here. ZnH5MD does not convert units and we assume ASE units everywhere.
=> [MDAnalysis fix]: Do not save units

apax/md/ase_calc.py
When calling batch eval in a loop, the OTFInMemoryDataset would leak memory. I swtched it with the cached dataset.
=> switch ase batch predict to CachedDataset

apax/cli/apax_app.py
removes the url from the valiation errors
example
```
apax validate train train . yaml
>>> 3 validation errors for config
>>> n_epochs
>>>     Field required
>>>     input_type: dict
>>> nepochs
>>>     Extra inputs are not permitted
>>>     input_type: int
>>>     input: 1000
>>> data . directory
>>>     Field required
>>>     input_type: dict
>>> Configuration Invalid !
```
=> cleaned up validation error messages

apax/layers/descriptor/gaussian_moment_descriptor.py
the indexing performed using the TRIL indices was not supported by jax originally (or maybe I was doing something wrong).
Whatever the case, it was now possible to significantly clean up the GM implementation. Training results and timings are exactly the same.
=> cleaned up gm implementation

examples/03_Transfer_Learning.ipynb
Someone should look into the writing of the word `apax` and decide if they want to write it capitalized or not as there is currently no consistency.
=> Fix Grammar in Docs

apax/nodes/selection.py
Should fix #384 but I have not tested it locally.
=> use `.parameter`

apax/nodes/model.py
=> ApaxImport node fix

apax/calibration.py, apax/nodes/model.py
@M-R-Schaefer or would it be better to return the `1/e_factor` from `compute_calibration_factors` directly?
=> fix apax calibrate metrics
